import type { Metadata } from "next";
import { Dosis, Roboto, Cinzel } from 'next/font/google';
import { Header } from "@/components/Header";
import "./index.scss";

const dosis = Dosis({ subsets: ['latin'], weight: ['200', '300', '400', '500', '600', '700', '800'] });
const roboto = Roboto({ subsets: ['latin'], weight: ['300', '400', '900'] });
const cinzel = Cinzel({ subsets: ['latin'], weight: ['400', '500', '600', '700', '800', '900'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`body-tag ${dosis.className} ${roboto.className} ${cinzel.className}`}>
        <Header></Header>
        <div className='page-content'>
          {children}
        </div>
      </body>
    </html>
  );
}
